idf_component_register(SRCS "main.c"
                            "hardware/iot154_battery.c"
                            "hardware/iot154_boot_button.c"
                            "hardware/iot154_pairing_led.c"
                            "hardware/iot154_sensor_input.c"
                            "metrics/iot154_metrics.c"
                            "power/iot154_power.c"
                            "radio/iot154_sensor_client.c"
                            "storage/iot154_storage.c"
                       INCLUDE_DIRS "."
                                    "config"
                                    "hardware"
                                    "metrics"
                                    "power"
                                    "radio"
                                    "storage"
                       REQUIRES iot154 nvs_flash esp_driver_gpio
                       PRIV_REQUIRES ieee802154 esp_timer esp_hw_support esp_adc)
