idf_component_register(
    SRCS
        "src/issp154_transport.c"
        "src/issp154_transport.cpp"
        "src/issp154_report_executor.cpp"
        "src/issp154_destination_manager.cpp"
        "src/issp154_mac_frame.c"
        "src/iot154_radio.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "src"
    REQUIRES
        ieee802154
        issp_core
        nvs_flash
)
